{
 "title": "Message Bus",
 "description": "Message Bus (msgbus) Dashboard",
 "tags": [ "msgbus" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "How long the msgbus has been up for",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "format": "dtdurationms",
   "valueName": "current",
   "targets": [
    { "expr": "msgbus_server_uptime / 1e6" }
   ]
  },
  {
   "title": "Requests",
   "type": "singlestat",
   "description": "Total number of HTTP requests processed",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "msgbus_http_requests" }
   ]
  },
  {
   "title": "Messages",
   "type": "singlestat",
   "description": "Total number of  messages exchanged",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "msgbus_bus_messages" }
   ]
  },
  {
   "title": "Topics",
   "type": "singlestat",
   "description": "Total number of  active topics",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "msgbus_bus_topics" }
   ]
  },
  {
   "title": "Subscribers",
   "type": "singlestat",
   "description": "Total number of  active subscribers",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "msgbus_bus_subscribers" }
   ]
  },
  {
   "title": "Rates",
   "type": "graph",
   "description": "Rates of messages exchanged and incoming requests",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "irate(msgbus_bus_messages[5m])", "legendFormat": "messages/s" },
    {
     "expr": "irate(msgbus_http_requests[5m])",
     "legendFormat": "requests/s"
    }
   ]
  },
  {
   "title": "Trends",
   "type": "graph",
   "description": "Trend of messages, topics, subscribers",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "msgbus_bus_messages", "legendFormat": "messages" },
    { "expr": "msgbus_bus_subscribers", "legendFormat": "subscribers" },
    { "expr": "msgbus_bus_topics" },
    { "expr": "msgbus_http_requests", "legendFormat": "requests" }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "description": "Memory usage of process (resident, virtual)",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"msgbus\"}",
     "legendFormat": "rss"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"msgbus\"}",
     "legendFormat": "vm"
    }
   ]
  },
  {
   "title": "Memory Allocations",
   "type": "graph",
   "description": "Memory allocations (bytes, heap, stack)",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"msgbus\"}",
     "legendFormat": "bytes"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"msgbus\"}",
     "legendFormat": "heap"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"eris\"}",
     "legendFormat": "stack"
    }
   ]
  },
  {
   "title": "Threads / Goroutines",
   "type": "graph",
   "description": "Active threads / goroutines",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "go_threads{job=\"msgbus\"}",
     "legendFormat": "threads"
    },
    {
     "expr": "go_goroutines{job=\"msgbus\"}",
     "legendFormat": "goroutines"
    }
   ]
  },
  {
   "title": "GC Duration",
   "type": "graph",
   "description": "Garbage Collection duration",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds_sum{job=\"msgbus\"} / go_gc_duration_seconds_count{job=\"msgbus\"}",
     "legendFormat": "avg"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"msgbus\", quantile=\"0.25\"}",
     "legendFormat": "p25"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"msgbus\", quantile=\"0.5\"}",
     "legendFormat": "p50"
    },
    {
     "expr": "go_gc_duration_seconds{job=\"msgbus\", quantile=\"0.75\"}",
     "legendFormat": "p75"
    }
   ]
  }
 ]
}